"""Checks on the frontend's hand-written static files.

These live in Python because there is no frontend test suite, and because the failure they
guard against is invisible to the tools that do run. `tsc`, `vite build` and `oxlint` never
parse `public/` -- it is copied to `dist/` byte for byte -- so a malformed SVG ships, is
served with the right length and content type, and simply doesn't draw. A browser reports
nothing: it falls back to the default tab icon.
"""

import json
import struct
from pathlib import Path
from xml.etree import ElementTree

SVG_NS = "http://www.w3.org/2000/svg"
PUBLIC_DIR = Path(__file__).resolve().parent.parent / "frontend" / "public"


class TestFavicon:
    def test_is_well_formed_xml(self):
        # SVG is parsed strictly. A double hyphen inside a comment is the easy way to break
        # this -- XML forbids it, and the repo's prose style uses `--` as an em dash
        # everywhere else, so it arrives by habit.
        ElementTree.parse(PUBLIC_DIR / "favicon.svg")

    def test_draws_something(self):
        root = ElementTree.parse(PUBLIC_DIR / "favicon.svg").getroot()
        assert root.tag == f"{{{SVG_NS}}}svg"
        drawn = [
            el
            for el in root.iter()
            if el.tag.startswith(f"{{{SVG_NS}}}")
            and el.tag.rsplit("}", 1)[1] in {"path", "circle", "rect", "polyline", "polygon"}
        ]
        assert drawn, "favicon has no drawable shape"

    def test_is_sized_for_a_tab(self):
        # Designed at the size it's drawn at, not scaled down to it (see the file's own note).
        root = ElementTree.parse(PUBLIC_DIR / "favicon.svg").getroot()
        assert root.get("viewBox") == "0 0 16 16"

    def test_has_no_blur_filters(self):
        # The mark this replaced was fifteen feGaussianBlurs, none of which were visible at
        # 16px. Blur is also the most expensive filter SVG has.
        root = ElementTree.parse(PUBLIC_DIR / "favicon.svg").getroot()
        assert not [el for el in root.iter() if el.tag == f"{{{SVG_NS}}}feGaussianBlur"]


class TestRasterIcons:
    """The home-screen icons, which iOS needs as PNGs however good the SVG is.

    Generated by `frontend/icons/render.py`; these check the committed output is a real PNG
    of the right size, since a binary is the one thing a diff can't show you.
    """

    EXPECTED = {"apple-touch-icon.png": 180, "icon-192.png": 192, "icon-512.png": 512}

    def test_each_icon_is_a_png_of_the_declared_size(self):
        for name, size in self.EXPECTED.items():
            data = (PUBLIC_DIR / name).read_bytes()
            assert data[:8] == b"\x89PNG\r\n\x1a\n", f"{name} is not a PNG"
            # IHDR is always the first chunk: 8 bytes signature, 4 length, 4 tag, then w/h.
            width, height = struct.unpack(">II", data[16:24])
            assert (width, height) == (size, size), f"{name} is {width}x{height}"

    def test_icons_are_opaque(self):
        # Colour type 2 is RGB without alpha. iOS composites a transparent home-screen icon
        # onto black, which would put this mark on a black square.
        for name in self.EXPECTED:
            data = (PUBLIC_DIR / name).read_bytes()
            assert data[25] == 2, f"{name} has an alpha channel"


class TestWebManifest:
    def test_is_valid_json_and_points_at_files_that_exist(self):
        manifest = json.loads((PUBLIC_DIR / "site.webmanifest").read_text())
        assert manifest["icons"], "manifest declares no icons"
        for icon in manifest["icons"]:
            referenced = PUBLIC_DIR / icon["src"].lstrip("/")
            assert referenced.exists(), f"manifest points at missing {icon['src']}"

    def test_offers_a_maskable_icon(self):
        # Without one, Android draws the icon inside a white circle rather than masking it.
        manifest = json.loads((PUBLIC_DIR / "site.webmanifest").read_text())
        assert any(icon.get("purpose") == "maskable" for icon in manifest["icons"])


class TestIndexHtml:
    def test_links_the_icons_it_ships(self):
        html = (PUBLIC_DIR.parent / "index.html").read_text()
        for rel in ('rel="icon"', 'rel="apple-touch-icon"', 'rel="manifest"'):
            assert rel in html, f"index.html is missing {rel}"
